import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { Container } from "react-bootstrap";
import { ThemeProvider } from "next-themes";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "CRUD PRODUCT",
    template: "%s ",
  },

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Container fluid>
            <Row>
              <Col xs={10}>{children}</Col>
            </Row>
          </Container>
        </ThemeProvider> */}
       <div className="grid grid-cols-3 ">
  <div className="col-span-1">
    <SideBar />
  </div>
  <div className="col-span-2 mr-20 -ml-20">
    <Header />
    {children}
  </div>
</div>

        <>
        </>
      </body>
    </html>
  );
}
