import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './styles/globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer, Zoom } from 'react-toastify';
import { ThemeProvider } from 'next-themes';
import SideBar from '@/app/_components/SideBar';
import Header from '@/app/_components/Header';
const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    absolute: '',
    default: 'CRUD PRODUCT',
    template: '%s ',
  },

  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider attribute="class">
          <div className="grid grid-cols-3">
            <div className="col-span-1">
              <SideBar />
            </div>
            <div className="col-span-2 -ml-40 mr-20">
              <ToastContainer
                position="top-right"
                autoClose={1000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="light"
                className="mr-14"
                transition={Zoom}
              />
              <Header />
              {children}
            </div>
          </div>
        </ThemeProvider>

        <></>
      </body>
    </html>
  );
}
