import type { Metadata } from 'next';
import SideBar from '@/app/_components/SideBar';
import Header from '@/app/_components/Header';
export const metadata: Metadata = {
  title: {
    absolute: '',
    default: 'V-SPLUSH',
    template: '%s - V-SPLUSH ',
  },

  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <Header />
      <div className="w-1/6 sm:w-0">
        <SideBar />
      </div>
      <div className="h-full w-4/5 sm:w-full">{children}</div>
    </div>
  );
}

